# Create this new file
openapi: 3.0.3
info:
  title: E-commerce Shared Contracts & API
  version: 1.0.0
  description: Defines shared DTOs and API schemas for the E-commerce application services (Backend, Email, Payment).
paths: {} # Define actual API paths later if needed
components:
  schemas:
    # --- 1. Core Shared Components (Value Object Equivalents & Basic Types) ---
    Money:
      description: Represents a monetary value with currency.
      type: object
      required: [amount, currencyCode]
      properties:
        amount: { type: number, format: double, description: "Monetary amount (e.g., 19.99). Represents BigDecimal." }
        currencyCode: { type: string, pattern: "^[A-Z]{3}$", description: "ISO 4217 Currency Code (e.g., USD)." }
